### ISSUE TITLE
RuntimeError: The weights trying to be saved contained shared tensors [{'model.vision_embed_tokens.wte.weight', 'model.embed_tokens.weight'}]

### ISSUE THREAD

**Issue by kazuar** [kazuar/Phi3-Vision-ft#2]
When running the `finetune.sh` script with my own dataset, I encountered the following error during checkpoint / saving the model:
```
RuntimeError: The weights trying to be saved contained shared tensors [{'model.vision_embed_tokens.wte.weight', 
'model.embed_tokens.weight'}] that are mismatching the transformers base configuration.
Try saving using `safe_serialization=False` or remove this tensor sharing.
```

Setting `safe_serialization=False` resulted in a model that wasn't able to load.
@2U1 did you encounter this error? (opened it here because https://github.com/2U1/Phi3-Vision-ft doesn't have an issues tab)

**Comment by 2U1** [comment]
First, sorry I didn't know I had no issue tab. I've opend the issue tab now. 

Does your error occured while full-finetuning? I'm not getting the error for now, however it might be the issue caused by accelerator.  
Can you add 
```
from accelerate import Accelerator
a = Accelerator()
a.save_model(trainer.model, output_dir)
trainer.model.config.save_pretrained(output_dir)
``` 
in safe_save_model_for_hf_trainer instead `trainer.save_model(output_dir)`.

I'll get on working further with this issue.

**Comment by kazuar** [comment]
> Does your error occured while full-finetuning?

Yes, I'm running the [finetune.sh](https://github.com/2U1/Phi3-Vision-ft/blob/main/scripts/finetune.sh) script with my own data (just changed one of the parameters `num_train_epochs` to 4)

 >  I'm not getting the error for now, however it might be the issue caused by accelerator.

I'll restart the environment tomorrow and try again. Seems like a good idea!

@2U1 thanks for all the help!

**Comment by 2U1** [comment]
Also, another way is to comment the deepspeed part in the `safe_save_model_for_hf_trainer` function like this.
I couldn't run the full-finetuning for the gpu issue, so I couldn't exactly solve the issue for right now.  Let me know if one the following way solve this issue.

    # if trainer.deepspeed:
    #     from accelerate import Accelerator
    #     accelerator = Accelerator()
    #     accelerator.wait_for_everyone()
    #     torch.cuda.synchronize()
    #     # trainer.save_model(output_dir)
    #     accelerator.save(trainer.model, output_dir, max_shard_size = '5GB')
    #     trainer.model.config.save_pretrained(output_dir)
    #     trainer.processor.save_pretrained(output_dir)
    #     return


    state_dict = trainer.model.state_dict()
    if trainer.args.should_save:
        cpu_state_dict = {
            key: value.cpu()
            for key, value in state_dict.items()
        }
        del state_dict
        trainer._save(output_dir, state_dict=cpu_state_dict)  # noqa
        trainer.model.config.save_pretrained(output_dir)

**Comment by jjbuck** [comment]
Ran into the same issue with Phi 3.5 Vision. I posted about this over on the HF forums [https://discuss.huggingface.co/t/runtimeerror-when-saving-phi-3-5-vision-due-to-shared-tensors/116457]. 

Even just a very simple example runs into this:

```
from transformers import AutoModelForCausalLM
model_id = "microsoft/Phi-3.5-vision-instruct"
model = AutoModelForCausalLM.from_pretrained(
    model_id, device_map="cuda", trust_remote_code=True, torch_dtype="auto"
)
model.save_pretrained("out", safe_serialization=True)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/AWSBedrockScienceModelDistillationTraining/.venv/lib/python3.12/site-packages/transformers/modeling_utils.py", line 2958, in save_pretrained
    raise RuntimeError(
RuntimeError: The weights trying to be saved contained shared tensors [{'model.embed_tokens.weight', 'model.vision_embed_tokens.wte.weight'}] that are mismatching the transformers base configuration. Try saving using `safe_serialization=False` or remove this tensor sharing.
```

**Comment by 2U1** [comment]
@jjbuck If you want to save the model, this works.
You need to remove the wte weight. It' okay becuase when the model is loaded from the checkpoint, it will automatically copy the weight from the embedding wieght.
        
state_dict = model.state_dict()
state_dict = {k:v for k, v in state_dict.items() if "wte" not in k}
model.save_pretrained(args.save_model_path, state_dict=state_dict, safe_serialization=True)
processor.save_pretrained(args.save_model_path)

**Comment by jjbuck** [comment]
Thank you @2U1! That seems to have worked!

Do you have an opinion on how one should use the `transformers` library to save Phi 3/3.5 Vision? The call to the `Trainer` class's `save_model` method doesn't accommodate a `state_dict` argument (see https://github.com/huggingface/transformers/blob/main/src/transformers/trainer.py#L3719-L3768). Is there some heuristic that would allow us to determine programmatically that this type of saving logic is required?

**Comment by 2U1** [comment]
@jjbuck I created and used a new class by inheriting from a Trainer class.
